name: ci

on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

      - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v2.1.5
        with:
          go-version: 1.18
          check-latest: true

      - name: build
        run: |
          make apko
          ./apko version

      - uses: goreleaser/goreleaser-action@ff11ca24a9b39f2d36796d1fbd7a4e39c182630a # v2.8.1
        with:
          version: latest
          install-only: true

      - name: snapshot
        run: |
          make snapshot
          ./dist/apko-build_linux_amd64_v1/apko version
