name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.0.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - name: Test
      run: make test
